# Application name
spring.application.name=hovrApp

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hovrApp
spring.datasource.username=postgres
spring.datasource.password=gaurav
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensure data.sql runs AFTER JPA schema generation
spring.jpa.defer-datasource-initialization=true

# SQL Script Initialization
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.continue-on-error=false

# Server context path
server.servlet.context-path=/api/v1

server.port=8081
